---
# Cloudflare Pages Configuration
build:
  command: npm run build
  environment:
    NODE_ENV: production

# MIME type configurations
headers:
  "/*.js":
    Content-Type: application/javascript; charset=utf-8
    Cache-Control: public, max-age=31536000, immutable

  "/*.css":
    Content-Type: text/css; charset=utf-8
    Cache-Control: public, max-age=31536000, immutable

  "/assets/*":
    Content-Type: application/javascript; charset=utf-8
    Cache-Control: public, max-age=31536000, immutable

  "/sw.js":
    Content-Type: application/javascript; charset=utf-8
    Cache-Control: no-cache, no-store, must-revalidate

  "/manifest.json":
    Content-Type: application/manifest+json; charset=utf-8
    Cache-Control: public, max-age=86400

# Routing configuration
routes:
  - pattern: "/assets/*.(js|css|json)"
    headers:
      Content-Type: "auto"

  - pattern: "/*.(js|css|json)"
    headers:
      Content-Type: "auto"

  - pattern: "/*"
    headers:
      X-Frame-Options: DENY
      X-Content-Type-Options: nosniff
      Referrer-Policy: strict-origin-when-cross-origin
