# Cloudflare Pages Configuration
# KhoChuan POS Frontend

name = "khoaugment"
compatibility_date = "2024-12-01"
pages_build_output_dir = "dist"

[env.production]
name = "khoaugment"
pages_build_output_dir = "dist"


watch_dir = "src"

# Environment variables for build
[env.production.vars]
NODE_VERSION = "18"
NPM_VERSION = "9"
VITE_API_URL = "https://khochuan-pos-api.bangachieu2.workers.dev"
VITE_APP_NAME = "KhoChuan POS"
VITE_APP_VERSION = "1.0.0"
VITE_NODE_ENV = "production"
