name = "khoaugment-api"
main = "src/index.js"
compatibility_date = "2024-01-15"
compatibility_flags = ["nodejs_compat"]

[env.production]
name = "khoaugment-api"

[env.staging]
name = "khoaugment-api-staging"

# D1 Database Configuration
[[d1_databases]]
binding = "DB"
database_name = "pos-database"
database_id = "813d3eca-d422-40ed-9b8f-ce21b1785967" # Đã được cập nhật với ID thực
migrations_dir = "database/migrations"

# KV Storage Configuration
[[kv_namespaces]]
binding = "CACHE"
id = "46b31b2c6ca449aaa3114d0ebb4fe645" # ID từ KV namespace CACHE

[[kv_namespaces]]
binding = "SESSIONS"
id = "b4966461e07a48e981c78cf9f374fe4c" # ID từ KV namespace SESSIONS

# R2 Storage Configuration - Đã được bình luận vì chưa kích hoạt R2
# [[r2_buckets]]
# binding = "STORAGE"
# bucket_name = "khochuan-files"

# Production Environment Variables
[env.production.vars]
ENVIRONMENT = "production"
JWT_SECRET = "khoaugment-super-secret-jwt-key-production-2025-truongphat"
ENCRYPTION_KEY = "khoaugment-32-char-encryption-prod!"
API_VERSION = "v1"
CORS_ORIGIN = "https://khoaugment.pages.dev"
COMPANY_NAME = "Trường Phát Computer Hòa Bình"
COMPANY_ADDRESS = "123 Đường Trường Phát, Hòa Bình, Việt Nam"
COMPANY_PHONE = "+84-123-456-789"
COMPANY_EMAIL = "info@truongphat.com"
ADMIN_EMAIL = "admin@truongphat.com"
SUPPORT_EMAIL = "support@truongphat.com"

# Production environment configuration
[env.production.d1_databases]
binding = "DB"
database_name = "khoaugment-pos-db"
database_id = "your-production-database-id"

[env.production.kv_namespaces]
binding = "CACHE"
id = "your-production-kv-id"

[env.production.durable_objects]
bindings = [
  { name = "ANALYTICS", class_name = "AnalyticsCounter" }
]

# Development Environment Variables
[env.development.vars]
ENVIRONMENT = "development"
JWT_SECRET = "khoaugment-super-secret-jwt-key-development-2025-truongphat"
ENCRYPTION_KEY = "khoaugment-32-char-encryption-dev!!"
API_VERSION = "v1"
CORS_ORIGIN = "http://localhost:5173"
COMPANY_NAME = "Trường Phát Computer Hòa Bình"
COMPANY_ADDRESS = "123 Đường Trường Phát, Hòa Bình, Việt Nam"
COMPANY_PHONE = "+84-123-456-789"
COMPANY_EMAIL = "info@truongphat.com"
ADMIN_EMAIL = "admin@truongphat.com"
SUPPORT_EMAIL = "support@truongphat.com"

# Analytics Engine - Đã được bình luận vì chưa kích hoạt Analytics Engine
# [[analytics_engine_datasets]]
# binding = "ANALYTICS"
# dataset = "khochuan_events"

# Durable Objects
[[durable_objects.bindings]]
name = "REALTIME"
class_name = "RealtimeDurableObject"

# Durable Objects Migrations
[[migrations]]
tag = "v1"
new_sqlite_classes = ["RealtimeDurableObject"]

