name = "smart-pos-api"
main = "src/index.js"
compatibility_date = "2024-01-15"
compatibility_flags = ["nodejs_compat"]

[env.production]
name = "smart-pos-api"
route = { pattern = "api.smartpos.dev/*", zone_name = "smartpos.dev" }

[env.staging]
name = "smart-pos-api-staging"

# D1 Database Configuration
[[d1_databases]]
binding = "DB"
database_name = "smart-pos-db"
database_id = "dfd20fc4-d3a1-47f6-86fa-424fa5a68ca0"
migrations_dir = "database/migrations"

# KV Storage Configuration
[[kv_namespaces]]
binding = "CACHE"
id = "your-kv-namespace-id"
preview_id = "your-kv-preview-id"

[[kv_namespaces]]
binding = "SESSIONS"
id = "your-sessions-kv-id"
preview_id = "your-sessions-preview-id"

# R2 Storage Configuration
[[r2_buckets]]
binding = "STORAGE"
bucket_name = "smart-pos-files"

# Environment Variables
[vars]
ENVIRONMENT = "production"
JWT_SECRET = "your-jwt-secret-key"
ENCRYPTION_KEY = "your-encryption-key"
API_VERSION = "v1"
CORS_ORIGIN = "https://smartpos.pages.dev"

# AI Configuration
[ai]
binding = "AI"

# Durable Objects
[[durable_objects.bindings]]
name = "REALTIME"
class_name = "RealtimeHandler"

# Analytics Engine
[[analytics_engine_datasets]]
binding = "ANALYTICS"
dataset = "smart_pos_events"

# Services (for microservices communication)
[[services]]
binding = "PAYMENT_SERVICE"
service = "payment-processor"

# Limits and Performance
[build]
command = "npm run build"
cwd = "."

[placement]
mode = "smart"

# Development Configuration
[env.development]
name = "smart-pos-api-dev"
vars = { ENVIRONMENT = "development", CORS_ORIGIN = "http://localhost:3000" }