name = "khoaugment-backend"
main = "src/index.js"
compatibility_date = "2024-07-01"
compatibility_flags = ["nodejs_compat"]
minify = true
account_id = "5b62d10947844251d23e0eac532531dd"

[env.development]
name = "khoaugment-backend-dev"

[env.staging]
name = "khoaugment-backend-staging"

[env.production]
name = "khoaugment-backend-prod"

# Uncomment and configure these after successful initial deployment
# [[d1_databases]]
# binding = "DB"
# database_name = "khoaugment-db"
# database_id = "khoaugment-db"
# migrations_dir = "migrations"

# [[r2_buckets]]
# binding = "BUCKET"
# bucket_name = "khoaugment-assets"
# preview_bucket_name = "khoaugment-assets-preview"

# [[kv_namespaces]]
# binding = "CACHE"
# id = "CACHE"
# preview_id = "CACHE_PREVIEW"

[vars]
ENVIRONMENT = "development"
CORS_ORIGIN = "http://localhost:5173,https://khoaugment-pos.pages.dev"
MAX_FILE_SIZE = "10485760"
RATE_LIMIT_REQUESTS = "100"
RATE_LIMIT_WINDOW = "3600"

# Use wrangler secret put for sensitive values:
# wrangler secret put JWT_SECRET
# wrangler secret put ENCRYPTION_KEY
# wrangler secret put VNPAY_SECRET_KEY
# wrangler secret put MOMO_SECRET_KEY
# wrangler secret put ZALOPAY_SECRET_KEY

[build]
command = "npm run build"
cwd = "."
watch_dir = "src"

[triggers]
crons = ["0 0 * * *"]

