name = "khochuan-api"
main = "src/index.js"
compatibility_date = "2024-01-15"
compatibility_flags = ["nodejs_compat"]

[env.production]
name = "khochuan-api"

[env.staging]
name = "khochuan-api-staging"

# D1 Database Configuration
[[d1_databases]]
binding = "DB"
<<<<<<< HEAD
database_name = "smart-pos-db"
database_id = "dfd20fc4-d3a1-47f6-86fa-424fa5a68ca0"
migrations_dir = "database/migrations"
=======
database_name = "pos-database"
database_id = "813d3eca-d422-40ed-9b8f-ce21b1785967" # Đã được cập nhật với ID thực
>>>>>>> 6806c702f54d85aaf87695d8ea5a7e4205f1eb0c

# KV Storage Configuration
[[kv_namespaces]]
binding = "CACHE"
id = "46b31b2c6ca449aaa3114d0ebb4fe645" # ID từ KV namespace CACHE

[[kv_namespaces]]
binding = "SESSIONS"
id = "b4966461e07a48e981c78cf9f374fe4c" # ID từ KV namespace SESSIONS

# R2 Storage Configuration - Đã được bình luận vì chưa kích hoạt R2
# [[r2_buckets]]
# binding = "STORAGE"
# bucket_name = "khochuan-files"

# Environment Variables
[vars]
ENVIRONMENT = "production"
JWT_SECRET = "YOUR_JWT_SECRET" # Change this in production
API_VERSION = "v1"
CORS_ORIGIN = "https://khoaugment.pages.dev"

# Analytics Engine - Đã được bình luận vì chưa kích hoạt Analytics Engine
# [[analytics_engine_datasets]]
# binding = "ANALYTICS"
# dataset = "khochuan_events"

# Durable Objects
[[durable_objects.bindings]]
name = "REALTIME"
class_name = "RealtimeHandler"

# Durable Objects Migrations
[[migrations]]
tag = "v1"
new_sqlite_classes = ["RealtimeHandler"]

# Development Configuration
[env.development]
name = "khochuan-api-dev"
vars = { ENVIRONMENT = "development", CORS_ORIGIN = "http://localhost:5173" }