name = "khochuan-pos-api"
main = "src/index.js"
compatibility_date = "2024-01-15"
compatibility_flags = ["nodejs_compat"]

[env.production]
name = "khoaugment-api"

[env.staging]
name = "khoaugment-api-staging"

# D1 Database Configuration
[[d1_databases]]
binding = "DB"
database_name = "khochuan-pos-prod"
database_id = "7cedbbbb-d8f5-4a66-b238-9b8ace74b200" # Production database
migrations_dir = "database/migrations"

# KV Storage Configuration
[[kv_namespaces]]
binding = "CACHE"
id = "46b31b2c6ca449aaa3114d0ebb4fe645" # ID từ KV namespace CACHE

[[kv_namespaces]]
binding = "SESSIONS"
id = "b4966461e07a48e981c78cf9f374fe4c" # ID từ KV namespace SESSIONS

# R2 Storage Configuration - Đã được bình luận vì chưa kích hoạt R2
# [[r2_buckets]]
# binding = "STORAGE"
# bucket_name = "khochuan-files"

# Production Environment Variables
[env.production.vars]
ENVIRONMENT = "production"
JWT_SECRET = "khoaugment-super-secret-jwt-key-production-2025-truongphat"
SALT = "truongphat-computer-hoabinh-salt-2025"
ENCRYPTION_KEY = "khoaugment-32-char-encryption-prod!"
API_VERSION = "v1"
CORS_ORIGIN = "https://khoaugment.pages.dev"
COMPANY_NAME = "Trường Phát Computer Hòa Bình"
COMPANY_ADDRESS = "123 Đường Trường Phát, Hòa Bình, Việt Nam"
COMPANY_PHONE = "+84-123-456-789"
COMPANY_EMAIL = "info@truongphat.com"
ADMIN_EMAIL = "admin@truongphat.com"
SUPPORT_EMAIL = "support@truongphat.com"

# Production environment configuration
[[env.production.d1_databases]]
binding = "DB"
database_name = "khochuan-pos-prod"
database_id = "7cedbbbb-d8f5-4a66-b238-9b8ace74b200"

[[env.production.kv_namespaces]]
binding = "CACHE"
id = "46b31b2c6ca449aaa3114d0ebb4fe645"

[[env.production.kv_namespaces]]
binding = "SESSIONS"
id = "b4966461e07a48e981c78cf9f374fe4c"

# Development Environment Variables
[env.development.vars]
ENVIRONMENT = "development"
JWT_SECRET = "khoaugment-super-secret-jwt-key-development-2025-truongphat"
SALT = "truongphat-computer-hoabinh-salt-dev-2025"
ENCRYPTION_KEY = "khoaugment-32-char-encryption-dev!!"
API_VERSION = "v1"
CORS_ORIGIN = "http://localhost:5173"
COMPANY_NAME = "Trường Phát Computer Hòa Bình"
COMPANY_ADDRESS = "123 Đường Trường Phát, Hòa Bình, Việt Nam"
COMPANY_PHONE = "+84-123-456-789"
COMPANY_EMAIL = "info@truongphat.com"
ADMIN_EMAIL = "admin@truongphat.com"
SUPPORT_EMAIL = "support@truongphat.com"

# Development database configuration
[[env.development.d1_databases]]
binding = "DB"
database_name = "khochuan-pos-prod"
database_id = "7cedbbbb-d8f5-4a66-b238-9b8ace74b200"

[[env.development.kv_namespaces]]
binding = "CACHE"
id = "46b31b2c6ca449aaa3114d0ebb4fe645"

[[env.development.kv_namespaces]]
binding = "SESSIONS"
id = "b4966461e07a48e981c78cf9f374fe4c"

# Analytics Engine - Đã được bình luận vì chưa kích hoạt Analytics Engine
# [[analytics_engine_datasets]]
# binding = "ANALYTICS"
# dataset = "khochuan_events"

# Durable Objects - Temporarily disabled for deployment
# [[durable_objects.bindings]]
# name = "REALTIME"
# class_name = "RealtimeDurableObject"

# Durable Objects Migrations - Disabled
# [[migrations]]
# tag = "v2"
# deleted_classes = ["RealtimeHandler"]

