name = "khochuan-api"
main = "src/index.js"
compatibility_date = "2024-01-15"
compatibility_flags = ["nodejs_compat"]

[env.production]
name = "khochuan-api"

[env.staging]
name = "khochuan-api-staging"

# D1 Database Configuration
[[d1_databases]]
binding = "DB"
database_name = "pos-database"
database_id = "YOUR_D1_DATABASE_ID" # Update this after creating the database

# KV Storage Configuration
[[kv_namespaces]]
binding = "CACHE"
id = "YOUR_KV_NAMESPACE_ID" # Update this after creating the KV namespace

[[kv_namespaces]]
binding = "SESSIONS"
id = "YOUR_SESSIONS_KV_ID" # Update this after creating the KV namespace

# R2 Storage Configuration
[[r2_buckets]]
binding = "STORAGE"
bucket_name = "khochuan-files"

# Environment Variables
[vars]
ENVIRONMENT = "production"
JWT_SECRET = "YOUR_JWT_SECRET" # Change this in production
API_VERSION = "v1"
CORS_ORIGIN = "https://khochuan-pos.pages.dev"

# Analytics Engine
[[analytics_engine_datasets]]
binding = "ANALYTICS"
dataset = "khochuan_events"

# Durable Objects
[[durable_objects.bindings]]
name = "REALTIME"
class_name = "RealtimeHandler"

# Development Configuration
[env.development]
name = "khochuan-api-dev"
vars = { ENVIRONMENT = "development", CORS_ORIGIN = "http://localhost:5173" }