# Cloudflare Workers Configuration - Production
# KhoChuan POS System - Production Environment
# Trường Phát Computer Hòa Bình

name = "khochuan-pos-api"
main = "src/index.js"
compatibility_date = "2024-12-01"
compatibility_flags = ["nodejs_compat"]

# Production Worker Settings
[env.production]
name = "khochuan-pos-api-prod"
route = { pattern = "api.khochuan-pos.com/*", zone_name = "khochuan-pos.com" }

# Environment Variables for Production
[env.production.vars]
ENVIRONMENT = "production"
API_VERSION = "1.0.0"
CORS_ORIGIN = "https://khochuan-pos.com"
JWT_SECRET = "your-production-jwt-secret-here"
RATE_LIMIT_REQUESTS = "1000"
RATE_LIMIT_WINDOW = "3600"
LOG_LEVEL = "info"

# D1 Database - Production
[[env.production.d1_databases]]
binding = "DB"
database_name = "khochuan-pos-prod"
database_id = "your-production-database-id"

# KV Namespaces - Production
[[env.production.kv_namespaces]]
binding = "CACHE"
id = "your-production-cache-id"
preview_id = "your-production-cache-preview-id"

[[env.production.kv_namespaces]]
binding = "SESSIONS"
id = "your-production-sessions-id"
preview_id = "your-production-sessions-preview-id"

# R2 Buckets - Production
[[env.production.r2_buckets]]
binding = "UPLOADS"
bucket_name = "khochuan-pos-uploads-prod"

# Durable Objects - Production
[[env.production.durable_objects.bindings]]
name = "REALTIME"
class_name = "RealtimeDurableObject"

# Analytics Engine - Production
[[env.production.analytics_engine_datasets]]
binding = "ANALYTICS"

# Queue - Production
[[env.production.queues.producers]]
binding = "EMAIL_QUEUE"
queue = "khochuan-email-queue-prod"

# Cron Triggers - Production
[[env.production.triggers]]
cron = "0 0 * * *"  # Daily at midnight
route = "/cron/daily-reports"

[[env.production.triggers]]
cron = "0 */6 * * *"  # Every 6 hours
route = "/cron/inventory-alerts"

# Development Environment (for reference)
[env.development]
name = "khochuan-pos-api-dev"

[env.development.vars]
ENVIRONMENT = "development"
API_VERSION = "1.0.0-dev"
CORS_ORIGIN = "*"
JWT_SECRET = "dev-jwt-secret"
RATE_LIMIT_REQUESTS = "10000"
RATE_LIMIT_WINDOW = "3600"
LOG_LEVEL = "debug"

# D1 Database - Development
[[env.development.d1_databases]]
binding = "DB"
database_name = "pos-database"
database_id = "local-dev-database"

# KV Namespaces - Development
[[env.development.kv_namespaces]]
binding = "CACHE"
id = "dev-cache-id"

[[env.development.kv_namespaces]]
binding = "SESSIONS"
id = "dev-sessions-id"

# Durable Objects - Development
[[env.development.durable_objects.bindings]]
name = "REALTIME"
class_name = "RealtimeDurableObject"

# Local Development Settings
[env.development.vars]
DATABASE_URL = "file:./dev.db"

# Durable Objects Migrations
[[migrations]]
tag = "v1"
new_sqlite_classes = ["RealtimeDurableObject"]

# Build Configuration
[build]
command = "npm run build"
cwd = "."

# Miniflare Configuration for Local Development
[miniflare]
kv_persist = true
d1_persist = true
cache_persist = true

# Limits and Performance
[limits]
cpu_ms = 50
memory_mb = 128

# Observability
[observability]
enabled = true

# Placement
[placement]
mode = "smart"
